# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dfsService_pb2 as dfsService__pb2


class DFServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddFile = channel.unary_unary(
                '/DFService/AddFile',
                request_serializer=dfsService__pb2.UpdateRequest.SerializeToString,
                response_deserializer=dfsService__pb2.UpdateReply.FromString,
                )
        self.DeleteFile = channel.unary_unary(
                '/DFService/DeleteFile',
                request_serializer=dfsService__pb2.UpdateRequest.SerializeToString,
                response_deserializer=dfsService__pb2.UpdateReply.FromString,
                )
        self.GetFile = channel.unary_unary(
                '/DFService/GetFile',
                request_serializer=dfsService__pb2.GetReply.SerializeToString,
                response_deserializer=dfsService__pb2.GetReply.FromString,
                )


class DFServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DFServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddFile': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFile,
                    request_deserializer=dfsService__pb2.UpdateRequest.FromString,
                    response_serializer=dfsService__pb2.UpdateReply.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=dfsService__pb2.UpdateRequest.FromString,
                    response_serializer=dfsService__pb2.UpdateReply.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=dfsService__pb2.GetReply.FromString,
                    response_serializer=dfsService__pb2.GetReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DFService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DFService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DFService/AddFile',
            dfsService__pb2.UpdateRequest.SerializeToString,
            dfsService__pb2.UpdateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DFService/DeleteFile',
            dfsService__pb2.UpdateRequest.SerializeToString,
            dfsService__pb2.UpdateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DFService/GetFile',
            dfsService__pb2.GetReply.SerializeToString,
            dfsService__pb2.GetReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
